name = "RandomFunctions"
uuid = "ccc3390e-0675-40fc-8b56-b6e685de3a1c"
authors = ["Camilo García"]
version = "0.0.3"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"

[compat]
Primes = "0.5"
SnoopPrecompile = "1.0.1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
