name = "RandomFunctions"
uuid = "ccc3390e-0675-40fc-8b56-b6e685de3a1c"
authors = ["Camilo García"]
version = "0.1.0"

[deps]

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
